models/Translation.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "translation".
 *
 * @property int $id
 * @property string $name
 * @property string $name_en
 * @property string $name_kz
 */
class Translation extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'translation';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'name_en', 'name_kz'], 'required'],
            [['name', 'name_en', 'name_kz'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Текст',
            'name_en' => 'Текст (EN)',
            'name_kz' => 'Текст (KZ)',
        ];
    }

    public function getText(){
        $name = "name".Yii::$app->session["lang"];
        return $this->$name;
    }
}

views/partials/partner.php
<div class="container">
    <div class="row mt-5 mb-4">
        <div class="col-sm-12 col-md">
            <h2 class="about-h2"><?=Yii::$app->view->params['translation'][31]->text;?></h2>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="4000">
        <div class="carousel-inner">
            <? $status = 'active';$m=0;?>
            <? foreach (Yii::$app->view->params['partner'] as $v):?>
                <? $m++;?>
                <? if($m % 6 == 1):?>
                <div class="carousel-item <?=$status;?>">
                    <div class="container">
                        <div class="row">
                <? endif;?>
                            <div class="col-sm-12 col-md-4 separator classForDisplay">
								<div class="classforImage">		
                                <img src="<?=$v->getImage();?>">
								</div>
                                <h2 class="partners-name"><?=$v->getName();?></h2>
                                <a class="moreOfProductions" href="/partner?id=<?=$v->id;?>"><?=Yii::$app->view->params['translation'][39]->text;?></a>
                            </div>
                <? if($m % 6 == 0):?>
                        </div>
                    </div>
                </div>
                <? endif;?>
                <? $status = '';?>
            <? endforeach;?>

            <? if($m % 6 != 0):?>
                    </div>
                </div>
            </div>
            <? endif;?>

        </div>
        <div class="container">
            <div class="row">
                <div class="col-6 left-arrow">
                    <div class="left-bg">
                        <a class="" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </div>
                </div>
                <div class="col-6 right-arrow">
                    <div class="right-bg">
                        <a class="" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>